name: "Component Request"
description: "Request a new component or enhancement"
labels: ["triage", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a component request! 😎

        If you have an idea for a new component or notice something is not working as intended, you are in the right place!
  - type: input
    id: subject
    attributes:
      label: "Subject"
      description: "What is the subject of this component?"
      placeholder: "Header"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What should be added or changed about the component's subject?"
      placeholder: "Please add a header with accompanying links."
    validations:
      required: true
  - type: dropdown
    id: participate
    attributes:
      label: "Are you willing to participate in the development of this component and create a pull request?"
      options:
        - "Yes"
        - "No"
  - type: markdown
    attributes:
      value: |
        This issue will be automatically unassigned after two weeks have passed since it was assigned.
        Once unassigned, it may be picked up by someone else for work.
