export const cookieData = [
  {
    id: 1,
    description:
      "These essential cookies enable website functionality, like accessing secure areas and maintaining items in a shopping cart. Typically, they are first-party session cookies. Although consent is not needed, their purpose and necessity must be explained to users.",
    isChecked: true,
    isDisabled: true,
    tableData: [
      {
        cookie: "Genki_Dama",
        description: "This cookie is used for the Genki Dama.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Kamehameha",
        description: "This cookie is used for the Kamehameha.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Galick_Gun",
        description: "This cookie is used for the Galick Gun.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Vegeta",
      },
      {
        cookie: "Destructo_Disk",
        description: "This cookie is used for the Destructo Disc.",
        domain: "https://yamada-ui.com/",
        expiration: "1 year",
        provider: "Krillin",
      },
      {
        cookie: "Wolf_Fang_Fist",
        description: "This cookie is used for the Wolf Fang Fist.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Yamcha",
      },
      {
        cookie: "Tri_Beam",
        description: "This cookie is used for the Tri Beam.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Tien_Shinhan",
      },
      {
        cookie: "Android_Barrier",
        description: "This cookie is used for the Android Barrier.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Android_17",
      },
      {
        cookie: "Energy_Blast",
        description: "This cookie is used for the Energy Wave.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Android_18",
      },
      {
        cookie: "Special_Beam_Cannon",
        description: "This cookie is used for the Special Beam Cannon.",
        domain: "https://yamada-ui.com/",
        expiration: "Persistent",
        provider: "Piccolo",
      },
      {
        cookie: "Hellzone_Grenade",
        description: "This cookie is used for the Hellzone Grenade.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Piccolo",
      },
    ],
    title: "Strictly Necessary",
  },
  {
    id: 2,
    description:
      "These cookies allow a website to remember your past choices, such as your preferred language, region for weather reports, or your username and password for automatic login.",
    tableData: [
      {
        cookie: "Genki_Dama",
        description: "This cookie is used for the Genki Dama.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Kamehameha",
        description: "This cookie is used for the Kamehameha.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Galick_Gun",
        description: "This cookie is used for the Galick Gun.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Vegeta",
      },
    ],
    title: "Preferences",
  },
  {
    id: 3,
    description:
      "These cookies gather data on your website usage, such as the pages you visit and the links you click. This information is aggregated and anonymized, meaning it cannot identify you. They are used solely to improve website functionality and include cookies from third-party analytics services if used exclusively by the website owner.",
    tableData: [
      {
        cookie: "Genki_Dama",
        description: "This cookie is used for the Genki Dama.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Kamehameha",
        description: "This cookie is used for the Kamehameha.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Galick_Gun",
        description: "This cookie is used for the Galick Gun.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Vegeta",
      },
    ],
    title: "Statistics",
  },
  {
    id: 4,
    description:
      "These cookies track your online activity to help advertisers deliver more relevant ads or limit the number of times you see an ad. They can share this information with other organizations or advertisers. These are persistent cookies and are almost always from third parties.",
    tableData: [
      {
        cookie: "Genki_Dama",
        description: "This cookie is used for the Genki Dama.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Kamehameha",
        description: "This cookie is used for the Kamehameha.",
        domain: "https://yamada-ui.com/",
        expiration: "1 month",
        provider: "Son_Goku",
      },
      {
        cookie: "Galick_Gun",
        description: "This cookie is used for the Galick Gun.",
        domain: "https://yamada-ui.com/",
        expiration: "Session",
        provider: "Vegeta",
      },
    ],
    title: "Marketing",
  },
  {
    id: 5,
    description: "Other Cookies are cookies that do not belong to a category.",
    isDisabled: true,
    title: "Other",
  },
]
