import Head from "next/head";
import { GetStaticProps, NextPage } from "next";
import { Container, Heading, Link, List, ListItem, Text, VStack } from "@yamada-ui/react"
import { CategoriesGroup } from "@/data/types";
import { CATEGORIES } from "@/data/categories";

interface PageProps {
  data: {
    list: CategoriesGroup[]
  }
}

export const getStaticProps: GetStaticProps<PageProps> = async () => {
  const list: CategoriesGroup[] = CATEGORIES;
  const data: PageProps["data"] = {
    list
  }
  return {
    props: {
      data
    }
  } as { props: PageProps }
}

const Home: NextPage<PageProps> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Yamada Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          {
            data.list.map((group, i) => (
              <VStack key={`${group.name}-${i}`}>
                <Heading>{group.name}</Heading>
                <List>
                  {group.categories.map((category, j) => (
                    <ListItem key={`${category.name}-${j}`} display="flex" flexDir={"column"}>
                      <Text>{category.name}</Text>
                      <Link href={`/category/${category.slug}`}>{`/category/${category.slug}`}</Link>
                    </ListItem>
                  ))}
                </List>
              </VStack>
            ))
          }
        </Container>
      </main>
    </>
  );
}
export default Home