import Head from "next/head";
import { GetStaticProps, NextPage } from "next";
import { Container, Heading, Link, List, ListItem, Text } from "@yamada-ui/react"
import { getAllComponents } from "@/data/components";

interface ListItem {
  name: string;
  path: string;
}
interface PageProps {
  data: {
    list: ListItem[]
  }
}

export const getStaticProps: GetStaticProps<PageProps> = async () => {
  const list: ListItem[] = (await getAllComponents()).map((e) => ({ name: e!.slug.charAt(0).toUpperCase() + e!.slug.slice(1).toLowerCase(), path: `/component/${e!.slug}` }))
  const data: PageProps["data"] = {
    list
  }
  return {
    props: {
      data
    }
  } as { props: PageProps }
}

const Home: NextPage<PageProps> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Yamada Components</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>コンポーネント一覧</Heading>
          <List>
            {data.list.map((e,i) => (
              <ListItem key={`${e.name}-${i}`} display="flex" flexDir={"column"}>
                <Text>{e.name}</Text>
                <Link href={e.path}>{e.path}</Link>
              </ListItem>
            ))}
          </List>
        </Container>
      </main>
    </>
  );
}
export default Home